// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyZXfrEB_hbcEBANGbA1dAGvQ2kzFT0w',
    appId: '1:354899209258:web:60e51f9997987ffd5b6753',
    messagingSenderId: '354899209258',
    projectId: 'grocery-app-99429',
    authDomain: 'grocery-app-99429.firebaseapp.com',
    storageBucket: 'grocery-app-99429.appspot.com',
    measurementId: 'G-K7P59ZE0BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34TQ4rnYiCo4DkM0Q_NfT4NRLL23Zpr0',
    appId: '1:354899209258:android:1c0842de7aabe1d35b6753',
    messagingSenderId: '354899209258',
    projectId: 'grocery-app-99429',
    storageBucket: 'grocery-app-99429.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrdhQa9SZCB_Zh8AaNiiFQ4LBeDBRFWs',
    appId: '1:354899209258:ios:012ccf6095fe60925b6753',
    messagingSenderId: '354899209258',
    projectId: 'grocery-app-99429',
    storageBucket: 'grocery-app-99429.appspot.com',
    iosClientId: '354899209258-1gjmej38lmeuag0lt4un4ecndgdva1ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrdhQa9SZCB_Zh8AaNiiFQ4LBeDBRFWs',
    appId: '1:354899209258:ios:012ccf6095fe60925b6753',
    messagingSenderId: '354899209258',
    projectId: 'grocery-app-99429',
    storageBucket: 'grocery-app-99429.appspot.com',
    iosClientId: '354899209258-1gjmej38lmeuag0lt4un4ecndgdva1ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
